### PR TITLE
update jenkins-k8s-node to  1.1.0

### PR DESCRIPTION
**Pull request by pydevops**

### CODE REVIEW

**Comment by pydevops** [comment]
test this please

**Comment by pydevops** [comment]
test this please

**Comment by chrislovecnm** [comment]
CI failed

**Comment by pydevops** [comment]
test this please

**Comment by pydevops** [comment]
@geojaz I have fixed the hardcoded and get GKE latest_master_version dynamically like in other demos. It passed the test today.

**Pull request merged**
