### PR TITLE
Remove cert outputs from terraform

### PR DESCRIPTION
**Pull request by venkayya**

### CODE REVIEW

**Comment by venkayya** [comment]
test this

**Comment by chrislovecnm** [comment]
Test this please

**Comment by chrislovecnm** [comment]
This should have passed by now. Please research

**Comment by venkayya** [comment]
test this please

**Comment by venkayya** [comment]
this has been passing CI but status is not getting updated

**Comment by venkayya** [comment]
test this please

**Comment by emailbob** [comment]
Try updating validate.sh with !/bin/bash -e at the top and then running it locally. The script is bombing out after step 2

**Comment by venkayya** [comment]
this PR passed CI

**Pull request merged**
